component excludeFromHelp=true extends="coldbox-cli.models.BaseCommand" {

	function run(){
		showColdBoxBanner( "AI Integration" )
		print.line();
		print
			.boldCyan( "ColdBox AI Integration Commands" )
			.line()
			.line()
			.whiteLine( "Enhance your development workflow with AI-powered assistants" )
			.line()
			.boldWhiteLine( "Setup & Management:" )
			.line()
			.greenLine( "  coldbox ai install          Set up AI integration for your project" )
			.greenLine( "  coldbox ai uninstall        Remove AI integration from your project" )
			.greenLine( "  coldbox ai refresh          Sync guidelines and skills with installed modules" )
			.greenLine( "  coldbox ai info             Display current AI configuration" )
			.greenLine( "  coldbox ai doctor           Diagnose AI integration health" )
			.greenLine( "  coldbox ai tree             Display AI structure as visual tree" )
			.greenLine( "  coldbox ai stats            Show context usage and statistics" )
			.line()
			.boldWhiteLine( "Component Management:" )
			.line()
			.greenLine( "  coldbox ai agents           Manage AI agent configurations (Claude, Copilot, etc.)" )
			.greenLine( "  coldbox ai guidelines       Manage framework guidelines and documentation" )
			.greenLine( "  coldbox ai skills           Manage AI skills (how-to cookbooks)" )
			.greenLine( "  coldbox ai mcp              Manage MCP documentation servers" )
			.line()
			.yellowLine( "Examples:" )
			.line()
			.dim( "  ## Set up AI integration with Claude" )
			.line( "  coldbox ai install --agent=claude" )
			.line()
			.dim( "  ## Add GitHub Copilot support" )
			.line( "  coldbox ai agents add copilot" )
			.line()
			.dim( "  ## List installed guidelines" )
			.line( "  coldbox ai guidelines list" )
			.line()
			.dim( "  ## View AI structure and statistics" )
			.line( "  coldbox ai tree" )
			.line( "  coldbox ai stats --verbose" )
			.line()
			.line()
			.yellowLine( "Tip: Type 'coldbox ai <command> --help' for detailed command information" )
			.line()
	}

}
