component excludeFromHelp=true extends="coldbox-cli.models.BaseCommand" {

	function run(){
		showColdBoxBanner( "AI Skills" )
		print.line();
		print
			.boldCyan( "AI Skills Management" )
			.line()
			.line()
			.whiteLine( "Skills are how-to cookbooks that guide AI assistants through specific tasks." )
			.whiteLine( "They are fetched from a central registry and stored locally in your project." )
			.line()
			.boldWhiteLine( "Commands:" )
			.line()
			.greenLine( "  coldbox ai skills find [query]           Search the skills registry" )
			.greenLine( "  coldbox ai skills install <slug>         Install skill(s) from the registry" )
			.greenLine( "  coldbox ai skills add <slug>             Alias for install" )
			.greenLine( "  coldbox ai skills list                   List installed skills" )
			.greenLine( "  coldbox ai skills list --outdated        Show skills with available updates" )
			.greenLine( "  coldbox ai skills refresh               Refresh/update all installed skills" )
			.greenLine( "  coldbox ai skills create <name>          Create a custom skill" )
			.greenLine( "  coldbox ai skills override <name>        Override an installed skill locally" )
			.greenLine( "  coldbox ai skills remove <name>          Remove a skill" )
			.line()
			.yellowLine( "Examples:" )
			.line()
			.dim( "  ## Search the registry" )
			.line( "  coldbox ai skills find testing" )
			.line( "  coldbox ai skills find --owner=coldbox --repo=skills" )
			.line()
			.dim( "  ## Install skills" )
			.line( "  coldbox ai skills install --list          ## interactive picker" )
			.line( "  coldbox ai skills install --all           ## install all core skills" )
			.line( "  coldbox ai skills install handler-development" )
			.line( "  coldbox ai skills install coldbox/skills/handler-development" )
			.line( "  coldbox ai skills add rest-api-development" )
			.line()
			.dim( "  ## List and check for updates" )
			.line( "  coldbox ai skills list" )
			.line( "  coldbox ai skills list --verbose" )
			.line( "  coldbox ai skills list --outdated" )
			.line()
			.dim( "  ## Create a custom skill" )
			.line( "  coldbox ai skills create deployment-workflow" )
			.line( "  coldbox ai skills create payment-processing --cfml" )
			.line()
			.dim( "  ## Override an installed skill with project-specific content" )
			.line( "  coldbox ai skills override handler-development" )
			.line()
			.dim( "  ## Remove a skill" )
			.line( "  coldbox ai skills remove handler-development" )
			.line()
			.dim( "  ## Refresh all installed skills to latest versions" )
			.line( "  coldbox ai skills refresh" )
			.line()
			.line()
			.yellowLine( "Skills are stored in (searched in this order):" )
			.line( "  .ai/skills/{name}/SKILL.md     - Primary location" )
			.line( "  .agents/skills/{name}/SKILL.md - Alternate (Windsurf/Cursor)" )
			.line( "  .claude/skills/{name}/SKILL.md  - Alternate (Claude desktop)" )
			.line()
			.line()
			.yellowLine( "Tip: Skills complement guidelines — guidelines explain 'what', skills explain 'how'" )
			.line()
	}

}
