component excludeFromHelp=true extends="coldbox-cli.models.BaseCommand" {

	function run(){
		showColdBoxBanner( "AI Agents" )
		print.line();
		print
			.boldCyan( "AI Agent Management" )
			.line()
			.line()
			.whiteLine( "Configure AI agents that use your project's guidelines and skills" )
			.line()
			.boldWhiteLine( "Supported Agents:" )
			.line()
			.line( "  • Claude (Anthropic) - Recommended for general development" )
			.line( "  • GitHub Copilot - Integrated with VS Code" )
			.line( "  • Cursor AI - AI-first code editor" )
			.line( "  • Codex (OpenAI) - GPT-powered assistant" )
			.line( "  • Gemini (Google) - Google's AI assistant" )
			.line( "  • OpenCode - Open source AI assistant" )
			.line()
			.boldWhiteLine( "Commands:" )
			.line()
			.greenLine( "  coldbox ai agents add <agent>       Add an agent to your project" )
			.greenLine( "  coldbox ai agents remove <agent>    Remove an agent configuration" )
			.greenLine( "  coldbox ai agents list              List configured agents" )
			.greenLine( "  coldbox ai agents active <agent>    Set the active agent" )
			.greenLine( "  coldbox ai agents open [agent]      Open agent config in editor" )
			.line()
			.yellowLine( "Examples:" )
			.line()
			.dim( "  ## Add GitHub Copilot" )
			.line( "  coldbox ai agents add copilot" )
			.line()
			.dim( "  ## Add multiple agents" )
			.line( "  coldbox ai agents add claude,cursor" )
			.line()
			.dim( "  ## Switch active agent to Cursor" )
			.line( "  coldbox ai agents active cursor" )
			.line()
			.dim( "  ## See all configured agents" )
			.line( "  coldbox ai agents list" )
			.line()
			.dim( "  ## Open active agent config" )
			.line( "  coldbox ai agents open" )
			.line()
			.line()
			.yellowLine( "Note: Each agent creates its own configuration file:" )
			.line( "  Claude: CLAUDE.md" )
			.line( "  Copilot: .github/copilot-instructions.md" )
			.line( "  Cursor: .cursorrules" )
			.line()
	}

}
